# Generated by Django 5.1.1 on 2024-10-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_complete',
        ),
    ]
